account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('panel/', panel, name='panel'),
    path('export_excel/', export_excel, name='export-excel'),
    path('search_result/', search_result, name='search-result'),
    path('panel/sort/<str:field>', sort, name='sort'),
    path('resume/', resume, name='resume'),
    path('skill/create/', create_skill, name='create-skill'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
]

templates/partials/navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        {% if user.is_authenticated %}
            {% if user.first_name and user.last_name %}
                <a class="navbar-brand" style="font-weight: bold;" href="/">{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</a>
            {% else %}
                <a class="navbar-brand" style="font-weight: bold;" href="/">{{ user.username|capfirst }}</a>
            {% endif %}
            <a class="btn btn-danger" style="font-weight: bold;" href="{% url 'account:logout' %}">Logout</a>
            </form>
        {% else %}
            <a class="navbar-brand" style="font-weight: bold;" href="/">Main Page</a>
        {% endif %}
    </div>
</nav>