account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('panel/', panel, name='panel'),
    path('export_excel/', export_excel, name='export-excel'),
    path('search_result/', search_result, name='search-result'),
    path('panel/sort/<str:field>', sort, name='sort'),
    path('resume/', resume, name='resume'),
    path('skill/create/', create_skill, name='create-skill'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
]

templates/cvmaker/index.html
{% extends 'base.html' %}

{% block title %} | Main Page{% endblock %}

{% block content %}

<div class ="card text-center">
    <div class="card-header">
        <h1><strong>CVMayker</strong></h1>
    </div>
    <div class ="card-body">

        <h4>CVMayker is a django app which job-seekers can make their CVs and send them to HRs</h4>
        <h4>HRs are also capable to check the received CVs in their panel</h4>
        <h4>Developed by <strong><a href="https://github.com/EngRobot33">Hamed Khosravi</a></strong></h4>

<br>

        <a class ="btn btn-primary" href ="{% url 'account:resume' %}"><h4><strong>Make CV</strong></h4></a>
        <a class ="btn btn-primary" href ="{% url 'account:login' %}"><h4><strong>HR Log-In</strong></h4></a>
    </div>
</div>
{% endblock %}

templates/cvmaker/login.html
{% extends "base.html" %}

{% block title %} | HR Login{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class ="card text-center">
    <div class="card-header">
        <h1><strong>CVMayker</strong></h1>
    </div>
    <div class ="card-body">
        <h2><strong>HR Log-In</strong></h2><br>

  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button class="btn btn-primary" type="submit"><strong>Log-In</strong></button>
  </form>

    </div>
</div>

{% endblock %}

templates/cvmaker/panel.html
{% extends 'base.html' %}

{% block title %} | HR Panel{% endblock %}

{% block content %}
    <h1>Job-seekers</h1>
    <br>
    <form class="d-flex" method="POST" action="{% url 'account:search-result' %}"> {% csrf_token %}
              <div class="input-group">
                <input type="text" class="form-control" name="searched" placeholder="Search Job-seekers">
                <div class="input-group-btn">
                  <button class="btn btn-warning" type="submit"><strong>Search</strong></button>
                </div>
              </div>
    </form>
    <br>
    <table style="text-align: center" class="table">
    {% if jobseekers %}
        <tr style="background-color: #0275d8; color: white;">
            <th><a href="{% url 'account:sort' 'first_name' %}" style="color: white">First Name</a></th>
            <th><a href="{% url 'account:sort' 'last_name' %}" style="color: white">Last Name</a></th>
            <th><a href="{% url 'account:sort' 'email' %}" style="color: white">E-mail</a></th>
            <th><a href="{% url 'account:sort' 'phone_number' %}" style="color: white">Phone Number</a></th>
            <th>Skills</th>
            <th>Projects</th>
        </tr>
        {% for js in jobseekers %}
            <tr>
                <th>{{ js.first_name }}</th>
                <th>{{ js.last_name }}</th>
                <th><a href="mailto:{{ js.email }}">{{ js.email }}</a></th>
                <th><a href="tel:{{ js.phone_number }}">{{ js.phone_number }}</a></th>
                <th>
                    {% for skill in js.skills.all %}
                        {{ skill.title }}
                    {% endfor %}
                </th>
                <th><a href="{{ js.project.link }}">{{ js.project }}</a></th>
            </tr>
        {% endfor %}
    </table>
        <a href="{% url 'account:export-excel' %}" class="btn btn-success"><strong>Export Excel</strong></a>
    {% else %}
        <h3>There is no job-seeker yet!</h3>
    {% endif %}
{% endblock %}

templates/cvmaker/resume.html
{% extends 'base.html' %}

{% block title %} | HR Panel{% endblock %}

{% block content %}

    {% load crispy_forms_tags %}

    <div class ="card text-center">
        <div class="card-header">
            <h1><strong>CVMayker</strong></h1>
        </div>
        <div class ="card-body">
            <h2><strong>Make CV</strong></h2><br>
            <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
                {{ jobseeker_form|crispy }}
                <br>
                <p><a href="{% url 'account:create-skill' %}" class="btn btn-primary">
                    <strong>Create new skill</strong></a></p>
                <br><br>
                <h4><strong>Project</strong></h4><br>
                <!-- No need to add crispy to this form for showing each project at one line-->
                <p>{{ project_form }}</p>
               <br>
               <button class="btn btn-success" type="submit" ><strong>Send</strong></button>
            </form>
        </div>
        {% if messages %}
            {% for msg in messages %}
                <div class="alert alert-{{ message.tags }} alert-rounded">
                    {{ msg|safe }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

templates/cvmaker/search_result.html
{% extends 'base.html' %}

{% block title %} | Search Result{% endblock %}

{% block content %}
    {% if searched %}
        <h1>You have searched for <strong>{{ searched }}</strong></h1>
        <br>
            <table style="text-align: center" class="table">
                {% if jobseekers %}
                    <tr style="background-color: #ffc107">
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>E-mail</th>
                        <th>Phone Number</th>
                        <th>Skills</th>
                        <th>Projects</th>
                    </tr>
                    {% for js in jobseekers %}
                        <tr>
                            <th>{{ js.first_name }}</th>
                            <th>{{ js.last_name }}</th>
                            <th><a href="mailto:{{ js.email }}">{{ js.email }}</a></th>
                            <th><a href="tel:{{ js.phone_number }}">{{ js.phone_number }}</a></th>
                            <th>
                                {% for skill in js.skills.all %}
                                    {{ skill.title }}
                                {% endfor %}
                            </th>
                            <th><a href="{{ js.project.link }}">{{ js.project }}</a></th>
                        </tr>
                    {% endfor %}
                {% else %}
                {% endif %}
            </table>
    {% else %}
        <p><h1>Hey! You forgot to search for a job-seeker</h1></p>
    {% endif %}
    <p>
    <a href="{% url 'account:panel' %}" class="btn btn-primary"><strong>Back to Main Panel</strong></a>
    </p>
{% endblock %}

templates/cvmaker/skill_create.html
{% extends 'base.html' %}

{% block title %} | Create Skill{% endblock %}

{% block content %}

    {% load crispy_forms_tags %}

    <div class ="card text-center">
        <div class ="card-body">
            <h1><strong>Create Skill</strong></h1><br>
            <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
                {{ form|crispy }}
                <br>
               <button class="btn btn-success" type="submit" ><strong>Create</strong></button>
            </form>
            <p>
                <a href="{% url 'account:resume' %}" class="btn btn-primary"><strong>Continue making CV</strong></a>
            </p>
        </div>
    </div>

{% endblock %}